server:
  port: ${port:8881}


xxl:
  job:
    admin:
      addresses: http://192.168.31.81:8888/xxl-job-admin
    executor:
      appname: my-xxl-job-executor-sample
      port: ${executor.port:9999}
