server:
  port: 8006
spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: leadnews
  redis:
    host: 112.124.153.122
    port: 6379
    password: 752557pkA
  application:
    name: heima-leadnews-search
  elasticsearch:
    rest:
      uris: http://localhost:9200
  cloud:
    nacos:
      server-addr: localhost:8848
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${spring.application.name}-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
