server:
  port: 8005
spring:
  application:
    name: heima-leadnews-schedule
  cloud:
    nacos:
      server-addr: localhost:8848
  datasource:
    password: 752557pkA
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.114.206.31:3306/leadnews_schedule?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  redis:
    host: 112.124.153.122
    port: 6379
    password: 752557pkA

mybatis-plus:
  type-aliases-package: com.heima.model.schedule.pojos
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

