version: "3.0"
services:

  "MyNacos":
    container_name: "MyNacos"
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
    image: nacos/nacos-server

  "myNginx":
    container_name: "myNginx"
    ports:
      - "9999:6000"
      - "9998:6001"
    volumes:
      - F:\kaifa\MyWorkspace\heima-leadnews-42\env\nginx\conf\nginx.conf:/etc/nginx/nginx.conf
      - F:\kaifa\MyWorkspace\heima-leadnews-42\env\nginx\html:/usr/share/nginx/html
    image: nginx

  "myMinio":
    container_name: "myMinio"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
    volumes:
      - F:\kaifa\MyWorkspace\heima-leadnews-42\env\minio:/data
    image: minio/minio
    command: server /data -console-address ":9001"

  "myMongo":
    container_name: "myMongo"
    ports:
      - "27017:27017"
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
    volumes:
      - F:\kaifa\MyWorkspace\heima-leadnews-42\env\mongo:/data
    image: mongo
